CREATE TABLE  "MARCA_CARRO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NOME" VARCHAR2(45) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "MODELO_CARRO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ANO" VARCHAR2(5) NOT NULL ENABLE, 
	"NOME" VARCHAR2(45) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "VEICULO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PLACA" VARCHAR2(45) NOT NULL ENABLE, 
	"COR" VARCHAR2(45) NOT NULL ENABLE, 
	"CHASSI" VARCHAR2(45) NOT NULL ENABLE, 
	"MODELO_CARRO_ID" NUMBER NOT NULL ENABLE, 
	"MARCA_CARRO_ID" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "CLIENTE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CPF" VARCHAR2(45) NOT NULL ENABLE, 
	"NOME" VARCHAR2(100) NOT NULL ENABLE, 
	"ENDERECO" VARCHAR2(45) NOT NULL ENABLE, 
	"DATA_NASC" DATE NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(45) NOT NULL ENABLE, 
	"TELEFONE" VARCHAR2(45) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "PRODUTO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NOME" VARCHAR2(45) NOT NULL ENABLE, 
	"VALOR" VARCHAR2(45) NOT NULL ENABLE, 
	"QTD_ESTOQUE" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "PEDIDO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"QTD_PRODUTOS" VARCHAR2(45), 
	"PRODUTO_ID" NUMBER NOT NULL ENABLE, 
	"CLIENTE_ID" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "MOTORISTA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CPF" VARCHAR2(45) NOT NULL ENABLE, 
	"NOME" VARCHAR2(100) NOT NULL ENABLE, 
	"ENDERECO" VARCHAR2(45) NOT NULL ENABLE, 
	"DATA_NASC" DATE NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(45) NOT NULL ENABLE, 
	"TELEFONE" VARCHAR2(45) NOT NULL ENABLE, 
	"CNH" VARCHAR2(45) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "SITUACAO" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NOME" VARCHAR2(45), 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
CREATE TABLE  "ENTREGA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"DATA_PARTIDA" DATE, 
	"DATA_ENTREGA" DATE, 
	"MOTORISTA_ID" NUMBER NOT NULL ENABLE, 
	"PEDIDO_ID" NUMBER NOT NULL ENABLE, 
	"VEICULO_ID" NUMBER NOT NULL ENABLE, 
	"SITUACAO_ID" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "ENTREGA" ADD CONSTRAINT "FK_ENTREGA_MOTORISTA1" FOREIGN KEY ("MOTORISTA_ID")
	  REFERENCES  "MOTORISTA" ("ID") ENABLE
/
ALTER TABLE  "ENTREGA" ADD CONSTRAINT "FK_ENTREGA_PEDIDO1" FOREIGN KEY ("PEDIDO_ID")
	  REFERENCES  "PEDIDO" ("ID") ENABLE
/
ALTER TABLE  "ENTREGA" ADD CONSTRAINT "FK_ENTREGA_VEICULO1" FOREIGN KEY ("VEICULO_ID")
	  REFERENCES  "VEICULO" ("ID") ENABLE
/
ALTER TABLE  "PEDIDO" ADD CONSTRAINT "FK_PEDIDO_CLIENTE1" FOREIGN KEY ("CLIENTE_ID")
	  REFERENCES  "CLIENTE" ("ID") ENABLE
/
ALTER TABLE  "PEDIDO" ADD CONSTRAINT "FK_PEDIDO_PRODUTO" FOREIGN KEY ("PRODUTO_ID")
	  REFERENCES  "PRODUTO" ("ID") ENABLE
/
ALTER TABLE  "ENTREGA" ADD CONSTRAINT "FK_PEDIDO_SITUACAO1" FOREIGN KEY ("SITUACAO_ID")
	  REFERENCES  "SITUACAO" ("ID") ENABLE
/
ALTER TABLE  "VEICULO" ADD CONSTRAINT "FK_VEICULO_MARCA_CARRO1" FOREIGN KEY ("MARCA_CARRO_ID")
	  REFERENCES  "MARCA_CARRO" ("ID") ENABLE
/
ALTER TABLE  "VEICULO" ADD CONSTRAINT "FK_VEICULO_MODELO_CARRO" FOREIGN KEY ("MODELO_CARRO_ID")
	  REFERENCES  "MODELO_CARRO" ("ID") ENABLE
/
Rem No function found to generate DDL.
CREATE UNIQUE INDEX  "SYS_C0084385313" ON  "CLIENTE" ("ID")
/
CREATE UNIQUE INDEX  "SYS_C0084385363" ON  "ENTREGA" ("ID")
/
CREATE UNIQUE INDEX  "SYS_C0084385867" ON  "VEICULO" ("ID")
/
CREATE UNIQUE INDEX  "SYS_C0084385904" ON  "MARCA_CARRO" ("ID")
/
CREATE UNIQUE INDEX  "SYS_C0084385915" ON  "MODELO_CARRO" ("ID")
/
CREATE UNIQUE INDEX  "SYS_C0084385957" ON  "MOTORISTA" ("ID")
/
CREATE UNIQUE INDEX  "SYS_C0084385991" ON  "PEDIDO" ("ID")
/
CREATE UNIQUE INDEX  "SYS_C0084386010" ON  "PRODUTO" ("ID")
/
CREATE UNIQUE INDEX  "SYS_C0084386012" ON  "SITUACAO" ("ID")
/
 CREATE SEQUENCE   "ALUNO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  GLOBAL
/
 CREATE SEQUENCE   "ALUNO_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  GLOBAL
/
 CREATE SEQUENCE   "ALUNO_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  GLOBAL
/
 CREATE SEQUENCE   "CLIENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  GLOBAL
/
 CREATE SEQUENCE   "ENTREGA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  GLOBAL
/
 CREATE SEQUENCE   "MARCA_CARRO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  GLOBAL
/
 CREATE SEQUENCE   "MODELO_CARRO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  GLOBAL
/
 CREATE SEQUENCE   "MOTORISTA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  GLOBAL
/
 CREATE SEQUENCE   "PEDIDO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE  NOKEEP  GLOBAL
/
 CREATE SEQUENCE   "PRODUTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  GLOBAL
/
 CREATE SEQUENCE   "SITUACAO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  GLOBAL
/
 CREATE SEQUENCE   "VEICULO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE  NOKEEP  GLOBAL
/
 CREATE SEQUENCE   "SEQ_TB_MATRICULA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE  NOKEEP  GLOBAL
/
 CREATE SEQUENCE   "SEQ_TB_ALUNO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 NOCACHE  NOORDER  NOCYCLE  NOKEEP  GLOBAL
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_CLIENTE" 
  before insert on CLIENTE               
  for each row  
begin   
  if :NEW.ID is null then 
    select CLIENTE_SEQ.nextval into :NEW.ID from dual; 
  end if; 
end;

/
ALTER TRIGGER  "BI_CLIENTE" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_ENTREGA" 
  before insert on ENTREGA
  for each row  
begin   
  if :NEW.ID is null then 
    select ENTREGA_SEQ.nextval into :NEW.ID from dual; 
  end if; 
end;

/
ALTER TRIGGER  "BI_ENTREGA" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_MARCA_CARRO" 
  before insert on MARCA_CARRO
  for each row  
begin   
  if :NEW.ID is null then 
    select MARCA_CARRO_SEQ.nextval into :NEW.ID from dual; 
  end if; 
end;

/
ALTER TRIGGER  "BI_MARCA_CARRO" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_MODELO_CARRO" 
  before insert on MODELO_CARRO
  for each row  
begin   
  if :NEW.ID is null then 
    select MODELO_CARRO_SEQ.nextval into :NEW.ID from dual; 
  end if; 
end;

/
ALTER TRIGGER  "BI_MODELO_CARRO" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_MOTORISTA_SEQ" 
  before insert on MOTORISTA
  for each row  
begin   
  if :NEW.ID is null then 
    select MOTORISTA_SEQ.nextval into :NEW.ID from dual; 
  end if; 
end;

/
ALTER TRIGGER  "BI_MOTORISTA_SEQ" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_PEDIDO_SEQ" 
  before insert on PEDIDO
  for each row  
begin   
  if :NEW.ID is null then 
    select PEDIDO_SEQ.nextval into :NEW.ID from dual; 
  end if; 
end;

/
ALTER TRIGGER  "BI_PEDIDO_SEQ" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_PRODUTO_SEQ" 
  before insert on PRODUTO
  for each row  
begin   
  if :NEW.ID is null then 
    select PRODUTO_SEQ.nextval into :NEW.ID from dual; 
  end if; 
end;

/
ALTER TRIGGER  "BI_PRODUTO_SEQ" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_SITUACAO" 
  before insert on SITUACAO
  for each row  
begin   
  if :NEW.ID is null then 
    select SITUACAO_SEQ.nextval into :NEW.ID from dual; 
  end if; 
end;

/
ALTER TRIGGER  "BI_SITUACAO" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_VEICULO" 
  before insert on VEICULO
  for each row  
begin   
  if :NEW.ID is null then 
    select VEICULO_SEQ.nextval into :NEW.ID from dual; 
  end if; 
end;

/
ALTER TRIGGER  "BI_VEICULO" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "ESTOQUE_PRODUTO" 
BEFORE
insert on "PEDIDO"
for each row
begin
    update produto set qtd_estoque = qtd_estoque - :new.qtd_produtos
    where  Produto.id=:new.produto_id;
end;

/
ALTER TRIGGER  "ESTOQUE_PRODUTO" ENABLE
/
CREATE OR REPLACE FORCE EDITIONABLE VIEW  "PEDIDO_COMPLETO" ("id", "Produto", "Quantidade_de_Produtos", "CLIENTE") AS 
  select pe.id, pt.nome as Produto, pe.qtd_produtos as Quantidade_de_Produtos, cli.nome as Cliente
	from Pedido pe, Produto pt, Cliente cli
	where pe.Produto_id = pt.id and pe.Cliente_id = cli.id
/